version: "3"
services:
  bitcoind:
    image: lncm/bitcoind:v24.0.1
    ports:
      - "18443:18443"
    volumes:
      - ${PWD}/dev/bitcoind/bitcoin.conf:/data/.bitcoin/bitcoin.conf
  lnd1:
    image: lightninglabs/lnd:v0.16.2-beta
    ports:
      - "10009:10009"
    volumes:
      - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
      - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
      - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
      - ${PWD}/dev/lnd/regtest/lnd1.wallet.db:/root/.lnd/wallet.db
      - ${PWD}/dev/lnd/regtest/lnd1.macaroons.db:/root/.lnd/macaroons.db
      - ${PWD}/dev/lnd/regtest/lnd1.admin.macaroon:/root/.lnd/admin.macaroon
    depends_on: [bitcoind]
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        mkdir -p /root/.lnd/data/chain/bitcoin/regtest/
        cp /root/.lnd/wallet.db /root/.lnd/data/chain/bitcoin/regtest/wallet.db
        cp /root/.lnd/macaroons.db /root/.lnd/data/chain/bitcoin/regtest/macaroons.db
        cp /root/.lnd/admin.macaroon /root/.lnd/data/chain/bitcoin/regtest/admin.macaroon
        /bin/lnd
